export const newsArray = [
    {
        "author": "Цензор.НЕТ",
        "title": "Еще 580 мировых компаний продолжают с Россией так называемый business as usual, - Кулеба",
        "description": "По подсчетам МИД Украины, из России ушли или прекратили сделки 1439 международных компаний из 70 стран и 55 различных индустрий.",
        "url": "https://censor.net/ru/news/3343447/esche_580_mirovyh_kompaniyi_prodoljayut_s_rossieyi_tak_nazyvaemyyi_business_as_usual_kuleba",
        "source": "Censor.net",
        "image": "https://storage1a.censor.net/images/9/f/6/4/9f64a3308de119275d98ea3425110477/original.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-05-24T09:19:53+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "Украинский транспортный самолет Ан-12, разбившийся в Греции, перевозил опасный груз по маршруту Сербия-Иордания-Бангладеш, - спикер МИД Николенко",
        "description": "Ночью на севере Греции потерпел крушение украинский транспортный самолет Ан-12, который перевозил опасный груз по маршруту Сербия-Иордания-Бангладеш.",
        "url": "https://censor.net/ru/news/3354630/ukrainskiyi_transportnyyi_samolet_an12_razbivshiyisya_v_gretsii_perevozil_opasnyyi_gruz_po_marshrutu",
        "source": "Censor.net",
        "image": "https://storage1.censor.net/images/6/5/f/8/65f84fdc36b5401df89dd8a787bcdd00/528x330.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-07-17T08:08:00+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "Благодаря западному оружию Украина снова может переломить ход войны, - The Washington Post",
        "description": "Западное оружие помогло украинским войскам замедлить продвижение российских войск, которое в настоящее время почти остановилось. У Украины появился шанс снова переломать ход войны в свою пользу, говорится в материале The Washington Post.",
        "url": "https://censor.net/ru/news/3357189/blagodarya_zapadnomu_orujiyu_ukraina_snova_mojet_perelomit_hod_voyiny_the_washington_post",
        "source": "Censor.net",
        "image": "https://storage1a.censor.net/images/6/9/7/f/697fb197d7ae011136605cb94175d3bd/528x330.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-07-28T18:16:00+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "26 мая сбита вражеская ракета Х-59, вертолет Ка-52 и беспилотник \"Орлан-10\", - Воздушные силы ВСУ",
        "description": "26 мая подразделения противовоздушной обороны ВСУ сбили крылатую ракету, вертолет и беспилотник российских оккупантов.",
        "url": "https://censor.net/ru/news/3344124/26_maya_sbita_vrajeskaya_raketa_h59_vertolet_ka52_i_bespilotnik_orlan10_vozdushnye_sily_vsu",
        "source": "Censor.net",
        "image": "https://storage1a.censor.net/images/e/b/5/c/eb5c136b7c99630533be0b292ca62274/original.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-05-26T20:45:37+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "Пентагон закупит для Украины ракеты с лазерной наводкой и беспилотники-разведчики, - The Washington Post",
        "description": "Пентагон расширяет поставки коммерческого оружия и военной техники в Украину. На $136 млн будут закуплены беспилотные летательные аппараты, ракеты с лазерной наводкой, бинокли.",
        "url": "https://censor.net/ru/news/3339745/pentagon_zakupit_dlya_ukrainy_rakety_s_lazernoyi_navodkoyi_i_bespilotnikirazvedchiki_the_washington",
        "source": "Censor.net",
        "image": "https://storage1.censor.net/images/c/5/5/9/c559c89fd62de6b9508cd9d3aecd3ba3/original.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-05-07T13:46:55+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "\"Хочу ще почути твоє рідне слово...\", - - защитник Мариуполя Казацкий поет под звуки обстрела песню победителя Евровидения-2022 Kalush Orchestra \"Стефанія\". ВИДЕО",
        "description": "Защитник Мариуполя Дмитрий Казацкий на \"Азовстали\" поет под звуки обстрела песню победителя Евровидения-2022 Kalush Orchestra \"Стефанія\".",
        "url": "https://censor.net/ru/news/3341664/hochu_sche_pochuti_tvo_rdne_slovo_zaschitnik_mariupolya_kazatskiyi_poet_pod_zvuki_obstrela_pesnyu_pobeditelya",
        "source": "Censor.net",
        "image": "https://storage2.censor.net/video/3/160522_azo.mp4",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-05-16T12:27:38+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "Флот России не сможет безопасно атаковать юг Украины без контроля над островом Змеиный, - The Wall Street Journal",
        "description": "Издание The Wall Street Journal посвятило редакционную статью освобождению острова Змеиный. Отмечается, что эта украинская победа не повлияет на ход войны, но ослабит российскую блокаду Черного моря.",
        "url": "https://censor.net/ru/news/3351599/flot_rossii_ne_smojet_bezopasno_atakovat_yug_ukrainy_bez_kontrolya_nad_ostrovom_zmeinyyi_the_wall_street",
        "source": "Censor.net",
        "image": "https://storage1.censor.net/images/2/5/1/e/251ec95f760c91f9d9332136ab28e2b3/528x330.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-07-01T20:36:00+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "\"Вы Homo Sapiens?\" - \"Нет. Я - русский\", - разговор с россиянином в соцсети. ВИДЕО",
        "description": "В сети опубликован фрагмент разговора с гражданином РФ, на котором он отвечает на вопрос, относится ли он к числу представителей вида Homo Sapiens (человек разумный).",
        "url": "https://censor.net/ru/video_news/3351174/vy_homo_sapiens_net_ya_russkiyi_razgovor_s_rossiyaninom_v_sotsseti_video",
        "source": "Censor.net",
        "image": "https://storage2.censor.net/video/3/300622_hom.mp4",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-06-30T08:01:00+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "Украина получит 4 HIMARS и 580 тактических беспилотников Phoenix Ghost, - Пентагон",
        "description": "Украина получит от Соединенных Штатов вооружение на сумму более 200 миллионов долларов.",
        "url": "https://censor.net/ru/news/3356497/ukraina_poluchit_4_himars_i_580_takticheskih_bespilotnikov_phoenix_ghost_pentagon",
        "source": "Censor.net",
        "image": "https://storage1.censor.net/images/8/a/5/9/8a59f280586df23706b00ff2f534869f/528x330.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-07-26T07:01:00+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "США планируют продать Украине четыре беспилотника \"MQ-1C Gray Eagle\", которые могут быть вооружены ракетами Hellfire, - Reuters",
        "description": "Администрация Байдена планирует продать Украине четыре беспилотника MQ-1C Grey Eagle, которые могут быть вооружены ракетами Hellfire для использования на поле боя против России.",
        "url": "https://censor.net/ru/news/3345394/ssha_planiruyut_prodat_ukraine_chetyre_bespilotnika_mq1c_gray_eagle_kotorye_mogut_byt_voorujeny_raketami",
        "source": "Censor.net",
        "image": "https://storage1.censor.net/images/6/2/0/3/620366f9dc0d5850214c6a65a7b362ac/original.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-06-01T20:41:42+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "\"Stop Russian oil & gas import\", - в Литве был создан плакат с призывом к введению эмбарго на российскую нефть и газ. ФОТО",
        "description": "Девушка из Литвы, небезразличная к судьбе Украины, вместе со своим другом разработали плакат с призывом остановить импорт российской нефти и газа.",
        "url": "https://censor.net/ru/photo_news/3341026/stop_russian_oil_gas_import_v_litve_byl_sozdan_plakat_s_prizyvom_k_vvedeniyu_embargo_na_rossiyiskuyu",
        "source": "Censor.net",
        "image": "https://storage1b.censor.net/images/a/3/4/3/a34346b02fb978694f7c9a93dc6d7538/original.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-05-13T09:39:54+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "США передадут Украине зенитные ракетные комплексы Patriot, - The Washington Post",
        "description": "По данным американского издания The Washington Post, США передадут Украине зенитные ракетные комплексы Patriot. ЗРК должны войти в новый пакет помощи в размере 40 млрд долларов, недавно одобренный Сенатом США.",
        "url": "https://censor.net/ru/news/3342749/ssha_peredadut_ukraine_zenitnye_raketnye_kompleksy_patriot_the_washington_post",
        "source": "Censor.net",
        "image": "https://storage1.censor.net/images/4/e/a/1/4ea1a6255b692bb18bbc1460127d16c9/original.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-05-20T18:00:59+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "Украинские Су-25 и Су-24м совершили несколько авианалетов на вражеские позиции. Уничтожены ротно-тактическая группа, техника и живая сила, - Воздушные силы",
        "description": "За минувшие сутки, 14 июня, зенитным ракетным подразделениям Воздушных Сил Вооруженных Сил Украины удалось уничтожить четыре крылатые ракеты, которые оккупанты запустили по территории Украины из акватории Черного моря.",
        "url": "https://censor.net/ru/news/3348019/ukrainskie_su25_i_su24m_sovershili_neskolko_avianaletov_na_vrajeskie_pozitsii_unichtojeny_rotnotakticheskaya",
        "source": "Censor.net",
        "image": "https://storage1a.censor.net/images/1/b/a/d/1bad30c5e1c7ab436c6a6ae232902ffd/original.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-06-15T06:01:26+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "США и союзники готовятся к длительной войне в Украине, Вашингтон стремится обеспечить, чтобы РФ не смогла победить, - The Washington Post",
        "description": "Соединенные Штаты Америки пытаются помешать победе России над Украиной.",
        "url": "https://censor.net/ru/news/3348751/ssha_i_soyuzniki_gotovyatsya_k_dlitelnoyi_voyine_v_ukraine_vashington_stremitsya_obespechit_chtoby_rf",
        "source": "Censor.net",
        "image": "https://storage1b.censor.net/images/e/d/c/7/edc7268acfd4d9b18335a67cb35cfb2e/original.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-06-18T14:21:00+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "Перспективы привлечения военных РФ к ответственности за военные преступления слабы, - The Wall Street Journal",
        "description": "Украина расследует более 16 000 случаев военных преступлений россиян в войне против Украины, но обвинила в них пока лишь небольшое количество человек. По данным Нацполиции, выявлено более 7500 подозреваемых, обвинения предъявлены 127 и только 15 из них находятся под стражей.",
        "url": "https://censor.net/ru/news/3356287/perspektivy_privlecheniya_voennyh_rf_k_otvetstvennosti_za_voennye_prestupleniya_slaby_the_wall_street",
        "source": "Censor.net",
        "image": "https://storage1.censor.net/images/5/b/7/3/5b739ddae8a58f5e98555898dc87e629/528x330.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-07-25T09:13:00+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "У ВСУ возникли проблемы с немецкими гаубицами PzH 2000, - Der Spiegel",
        "description": "Всего месяц спустя после поставки немецких самоходных артиллерийских установок (САУ) Panzerhaubitze 2000 (PzH 2000) в Украину эти артиллерийские орудия уже демонстрируют явные признаки износа, говорится в материале еженедельника Der Spiegel.",
        "url": "https://censor.net/ru/news/3357363/u_vsu_voznikli_problemy_s_nemetskimi_gaubitsami_pzh_2000_der_spiegel",
        "source": "Censor.net",
        "image": "https://storage1b.censor.net/images/5/2/d/2/52d221f2d233a26aad693a5f92587a88/528x330.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-07-29T15:03:00+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "Россия готовится запустить спутник-шпион для слежки за Украиной, - The Washington Post",
        "description": "Россия готовится запустить спутник-шпион. Он расширит возможности Ирана по наблюдению за военными целями на Ближнем Востоке.",
        "url": "https://censor.net/ru/news/3358724/rossiya_gotovitsya_zapustit_sputnikshpion_dlya_slejki_za_ukrainoyi_the_washington_post",
        "source": "Censor.net",
        "image": "https://storage1.censor.net/images/f/d/6/c/fd6c00557df029c4b6072bb0918a1916/528x330.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-08-05T08:57:00+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "США рассматривают передачу Украине РСЗО без дальнобойных ракет, - The Washington Post",
        "description": "По данным The Washington Post, США рассматривают возможность передачи Украине универсальных реактивных систем залпового огня, но без дальнобойных ракет.",
        "url": "https://censor.net/ru/news/3344905/ssha_rassmatrivayut_peredachu_ukraine_rszo_bez_dalnoboyinyh_raket_the_washington_post",
        "source": "Censor.net",
        "image": "https://storage1a.censor.net/images/f/b/9/2/fb927f51afa4e2d28ec463d71bbe38e7/original.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-05-30T20:59:03+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "ФБР начало расследование, как американские чипы оказались в российской военной технике, - The Washington Post",
        "description": "Федеральное бюро расследований США начало изучать, как компьютерные чипы американских технологических компаний оказались в российском военном оборудовании, изъятом в Украине.",
        "url": "https://censor.net/ru/news/3348464/fbr_nachalo_rassledovanie_kak_amerikanskie_chipy_okazalis_v_rossiyiskoyi_voennoyi_tehnike_the_washington",
        "source": "Censor.net",
        "image": "https://storage1.censor.net/images/c/2/6/6/c266a7dc9de7233d031bd72ad011ddf0/original.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-06-17T05:37:00+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "РФ, вероятно, скоро начнет масштабное наступление вдоль линии Славянск-Северск-Бахмут, - ISW",
        "description": "Россияне, вероятно, в скором времени начнут более масштабное и решительное наступление вдоль линии Славянск-Северск-Бахмут.",
        "url": "https://censor.net/ru/news/3354224/rf_veroyatno_skoro_nachnet_masshtabnoe_nastuplenie_vdol_linii_slavyanskseverskbahmut_isw",
        "source": "Censor.net",
        "image": "https://storage1a.censor.net/images/7/c/b/b/7cbb461214192c78215a733f331b5ee4/528x330.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-07-15T06:01:00+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "Война в Украине может закончиться через четыре-шесть месяцев. Далее - замороженный конфликт, - экс-командующий силами НАТО Ставридис",
        "description": "Бывший главнокомандующий силами НАТО в Европе Джеймс Ставридис считает, что война России против Украины, скорее всего, может закончиться через четыре-шесть месяцев. Дальше она может стать замороженным конфликтом по примеру Корейской войны.",
        "url": "https://censor.net/ru/news/3354769/voyina_v_ukraine_mojet_zakonchitsya_cherez_chetyreshest_mesyatsev_dalee_zamorojennyyi_konflikt_ekskomanduyuschiyi",
        "source": "Censor.net",
        "image": null,
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-07-18T07:46:00+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "Amnesty International сделала \"аморальную избирательность\", которая помогает государству-террористу, - Зеленский",
        "description": "Президент Украины Владимир Зеленский заявил, что доклад международной правозащитной организации Amnesty International о том, что украинская армия якобы подвергает опасности гражданское население страны, переводит ответственность с агрессора (России) на жертву (Украину).",
        "url": "https://censor.net/ru/news/3358677/amnesty_international_sdelala_amoralnuyu_izbiratelnost_kotoraya_pomogaet_gosudarstvuterroristu_zelenskiyi",
        "source": "Censor.net",
        "image": "https://storage1a.censor.net/images/9/1/9/4/9194597d967c287fdc0722696b579991/528x330.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-08-05T05:57:00+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "\"Нас уже нет почти - человек 50 из 800!.. Я #бал! Выбираться короче надо, нах#й! Тут только один выход - либо 200-й, либо 300-й\", - разговор оккупанта с женой. АУДИО",
        "description": "Украинские разведчики перехватили телефонный разговор российского оккупанта с женой, в котором он рассказывает о больших потерях подразделения и желании любыми путями выбраться из Украины.",
        "url": "https://censor.net/ru/video_news/3339483/nas_uje_net_pochti_chelovek_50_iz_800_ya_bal_vybiratsya_koroche_nado_nahyi_tut_tolko_odin_vyhod_libo",
        "source": "Censor.net",
        "image": "https://storage2.censor.net/video/3/060522_oku.mp4",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-05-06T14:05:55+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "США согласовали новый пакет военной помощи Украине, включая ракетные системы HIMARS, - The Washington Post",
        "description": "США 1 июня объявят о предоставлении Украине нового пакета военной помощи в 700 млн долларов. В него в частности войдут ракетные системы HIMARS.",
        "url": "https://censor.net/ru/news/3345187/ssha_soglasovali_novyyi_paket_voennoyi_pomoschi_ukraine_vklyuchaya_raketnye_sistemy_himars_the_washington",
        "source": "Censor.net",
        "image": "https://storage1b.censor.net/images/7/1/d/5/71d590d18f9922707cf5d2c7c017de02/original.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-06-01T05:48:28+00:00"
    },
    {
        "author": "Цензор.НЕТ",
        "title": "Сегодня в Мадриде для президентов всех стран НATO на саммите выступит украинский оркестр Kyiv Symphony Orchestra",
        "description": "За 73-летнюю историю существования Альянса Kyiv Symphony Orchestra стал вторым оркестром, который пригласили выступить на западе НАТО такого уровня.",
        "url": "https://censor.net/ru/news/3351004/segodnya_v_madride_dlya_prezidentov_vseh_stran_nato_na_sammite_vystupit_ukrainskiyi_orkestr_kyiv_symphony",
        "source": "Censor.net",
        "image": "https://storage1b.censor.net/images/6/8/5/7/685739473c2587e8cf4748b58a7fabc8/original.jpg",
        "category": "general",
        "language": "en",
        "country": "ua",
        "published_at": "2022-06-29T11:57:00+00:00"
    }
]